"""
enrich_gemini.py — Step 5: The Taste Rationale Generator.

Takes the raw mathematical/structural data (visual DNA, motion code, video metrics)
and uses Gemini to translate it into a structured set of Design Principles and a "Why" rationale.
This creates the "Architecture" summaries used in the recombination tests and Elo ranking.
"""
import sys
import os
import json
import time
from pathlib import Path
from google import genai

sys.path.insert(0, str(Path(__file__).parent.parent))

from rich.console import Console
from config import DATA_DIR

console = Console()

def get_api_key():
    # Force read from .env regardless of load_dotenv quirks
    env_path = Path(__file__).parent.parent / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            if line.startswith("GEMINI_API_KEY="):
                return line.split("=", 1)[1].strip()
    return os.environ.get("GEMINI_API_KEY")

API_KEY = get_api_key()
if not API_KEY or API_KEY == "your_key_here":
    console.print("[red]✗ GEMINI_API_KEY not found in .env file.[/red]")
    console.print("Make sure you saved the file! Get a free key at: https://aistudio.google.com/app/apikey")
    sys.exit(1)

# Initialize new SDK
client = genai.Client(api_key=API_KEY)

PROMPT_TEMPLATE = """
You are a senior art director and motion designer analyzing raw structural data extracted from a high-end website.
Your job is to translate this objective mathematical data into a set of exactly 4 "Design Principles" (snake_case) and a short "Why" rationale explaining how this data affects the user's subjective feeling of the site.

RAW DATA:
- Site ID: {site_id}
- Whitespace Ratio: {whitespace} (0 = entirely dense, 1.0 = entirely empty)
- Asymmetry Score: {asymmetry} (0 = perfectly centered/symmetric, 1.0 = extremely asymmetric layout)
- Average Brightness: {brightness} (0 = pitch black, 1.0 = pure white)
- Color Palette: {colors}
- Color Rhythm/Variance: {color_variance} (Low = monochromatic block, High = highly rhythmic/contrasting colors)
- Primary Typography: {primary_font} (Max size: {max_font_size}px)
- Layout Complexity: {total_nodes} DOM nodes in viewport (sparse vs brutalist dense)
- Media Assets Detected: Canvas(3D/WebGL): {canvas_count}, SVG: {svg_count}, Video: {video_count}, Img: {img_count}
- Loading Sequence: Content appeared at {content_start}s. {blank_frames} loading frames detected.
- Video Density: {video_size}MB (higher means heavier, continuous rendering)
- Motion Engine & Code Summary:
{motion_code}

Based STRICTLY on the data above, output the following format and nothing else:

### Category
[Classify the site into one of these strict categories: SaaS, E-Commerce, Editorial, Portfolio/Agency, WebGL/Experimental, Corporate, Other]

### Design Principles
* `[principle_1]`: [Short explanation based on data - e.g., spatial layout & symmetry]
* `[principle_2]`: [Short explanation based on data - e.g., media asset selection & canvas vs imagery]
* `[principle_3]`: [Short explanation based on data - e.g., typographic scale & density]
* `[principle_4]`: [Short explanation based on data - e.g., motion & color rhythm]

### The "Why"
[2-3 sentences explaining the subjective, emotional feel generated by this exact combination of math, typography, layout symmetry, and motion.]
"""

def generate_rationale(site_id: str):
    site_dir = DATA_DIR / site_id
    meta_path = site_dir / "metadata.json"
    visual_path = site_dir / "visual_analysis.json"
    motion_path = site_dir / "motion_code.json"
    frames_path = site_dir / "frames_manifest.json"

    if not visual_path.exists():
        return False
        
    try:
        visual = json.loads(visual_path.read_text())
        
        motion_summary = "None detected."
        if motion_path.exists():
            motion_data = json.loads(motion_path.read_text())
            has_gsap = motion_data.get("gsap_detected", False)
            css_count = len(motion_data.get("css_transitions", []))
            motion_summary = f"GSAP Detected: {has_gsap}. CSS Transitions: {css_count}."
            if css_count > 0:
                motion_summary += f"\nSample CSS: {json.dumps(motion_data['css_transitions'][:3])}"
                
        content_start = 0
        blank_frames = 0
        video_size = 0
        if frames_path.exists():
            frames_data = json.loads(frames_path.read_text())
            content_start = frames_data.get("content_start_s", 0)
            blank_frames = frames_data.get("blank_probe_count", 0)
            video_size = frames_data.get("video_size_mb", 0)

        colors = [c["hex"] for c in visual.get("palette", [])]
        
        meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}
        dom = meta.get("dom_structure", {})
        tags = dom.get("tags", {})
        typo = dom.get("typography", {})

        prompt = PROMPT_TEMPLATE.format(
            site_id=site_id,
            whitespace=round(visual.get("whitespace_ratio", 0), 3),
            asymmetry=round(visual.get("asymmetry_score", 0), 3),
            brightness=round(visual.get("avg_brightness", 0), 3),
            colors=", ".join(colors),
            color_variance=visual.get("color_variance", 0),
            primary_font=typo.get("primary_font", "unknown"),
            max_font_size=typo.get("max_font_size_px", 0),
            total_nodes=tags.get("total_nodes", 0),
            canvas_count=tags.get("canvas", 0),
            svg_count=tags.get("svg", 0),
            video_count=tags.get("video", 0),
            img_count=tags.get("img", 0),
            content_start=content_start,
            blank_frames=blank_frames,
            video_size=video_size,
            motion_code=motion_summary
        )

        out_path = site_dir / "taste_rationale.md"
        
        # Skip if already exists
        if out_path.exists():
            console.print(f"[yellow]⏭[/yellow] Skip {site_id} (rationale already exists)")
            return True
            
        console.print(f"[cyan]→[/cyan] Querying Gemini for {site_id}...")
        
        # New SDK syntax
        response = client.models.generate_content(
            model='gemini-3.6-flash',
            contents=prompt,
        )
        
        out_path.write_text(response.text)
        
        console.print(f"[green]✓[/green] Rationale saved for {site_id}")
        return True
        
    except Exception as e:
        console.print(f"[red]✗ Failed for {site_id}: {e}[/red]")
        return False

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate Taste Rationale using Gemini")
    parser.add_argument("--site", help="Process a single site ID")
    args = parser.parse_args()

    if args.site:
        generate_rationale(args.site)
    else:
        for site_dir in sorted(DATA_DIR.iterdir()):
            if site_dir.is_dir() and (site_dir / "metadata.json").exists():
                out_path = site_dir / "taste_rationale.md"
                if not out_path.exists():
                    success = generate_rationale(site_dir.name)
                    if success:
                        time.sleep(5)  # 12 RPM to stay safely under 15 RPM free tier limit
                    else:
                        time.sleep(60) # If it fails (likely rate limit), wait a full minute
                else:
                    console.print(f"[yellow]⏭[/yellow] Skip {site_dir.name}")
